language: python
python:
  - "3.8"

install: 
  - pip install -e .
  - pip install pytest-cov # Package to cov test

script:
  - pytest --cov=src tests # Point to source directory

after_success:
 - bash <(curl -s https://codecov.io/bash)

