language: python
python:
  - "3.8"

install: 
  - pip install -e .
  - pip install pytest-cov code-cov # Package to cov test

script:
  - pytest --cov=src tests # Point to source directory

after_success:
  - codecov # Uploads the report